
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install tzdata sudo
RUN apt-get install -y \
		bc \
		build-essential 

WORKDIR /catana
#COPY . /catana

CMD ["/bin/sleep", "infinity"]
